version: '3'

services:
  postgres:
    image: postgres
    network_mode: "host" # expose all
    environment:
      POSTGRES_DB: "temporal"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password123"
  temporalx:
    image: temporalx:latest
    network_mode: "host" # expose all
    depends_on:
      - postgres
  minio:
    image: rtradetech/s3x-minio:latest
    network_mode: "host" # expose all
    command: gateway s3x --temporalx.endpoint 127.0.0.1:9090 --temporalx.insecure true
    environment: 
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    depends_on:
      - temporalx